const products = [
    {
        "_id": "1",
        "id": "1",
        "stockNumber": "ST12345",
        "count": 10,
        "description": "Bike description",
        "manufacturer": "Manufacturer A",
        "partNumber": "PN12345",
        "price": 299.99,
        "name": "Україна - ABC123",
        "rate": 4.5,
        "wheelRadius": 27.5,
        "weight": 15.2
    },
    {
        "_id": "2",
        "id": "2",
        "stockNumber": "ST12346",
        "count": 15,
        "description": "Bike description",
        "manufacturer": "Manufacturer B",
        "partNumber": "PN12346",
        "price": 329.99,
        "name": "Україна - DEF456",
        "rate": 4.0,
        "wheelRadius": 26,
        "weight": 14.8
    },
    {
        "_id": "3",
        "id": "3",
        "stockNumber": "ST12347",
        "count": 5,
        "description": "Bike description",
        "manufacturer": "Manufacturer C",
        "partNumber": "PN12347",
        "price": 349.99,
        "name": "Україна - GHI789",
        "rate": 4.7,
        "wheelRadius": 29,
        "weight": 15.6
    },
    {
        "_id": "4",
        "id": "4",
        "stockNumber": "ST12348",
        "count": 20,
        "description": "Bike description",
        "manufacturer": "Manufacturer D",
        "partNumber": "PN12348",
        "price": 379.99,
        "name": "Україна - JKL012",
        "rate": 4.3,
        "wheelRadius": 27.5,
        "weight": 16.0
    },
    {
        "_id": "5",
        "id": "5",
        "stockNumber": "ST12349",
        "count": 8,
        "description": "Bike description",
        "manufacturer": "Manufacturer E",
        "partNumber": "PN12349",
        "price": 399.99,
        "name": "Україна - MNO345",
        "rate": 4.6,
        "wheelRadius": 26,
        "weight": 14.5
    },
    {
        "_id": "6",
        "id": "6",
        "stockNumber": "ST12350",
        "count": 12,
        "description": "Bike description",
        "manufacturer": "Manufacturer F",
        "partNumber": "PN12350",
        "price": 429.99,
        "name": "Україна - PQR678",
        "rate": 4.8,
        "wheelRadius": 29,
        "weight": 15.9
    },
    {
        "_id": "7",
        "id": "7",
        "stockNumber": "ST12351",
        "count": 7,
        "description": "Bike description",
        "manufacturer": "Manufacturer G",
        "partNumber": "PN12351",
        "price": 449.99,
        "name": "Україна - STU901",
        "rate": 4.2,
        "wheelRadius": 27.5,
        "weight": 15.4
    },
    {
        "_id": "8",
        "id": "8",
        "stockNumber": "ST12352",
        "count": 11,
        "description": "Bike description",
        "manufacturer": "Manufacturer H",
        "partNumber": "PN12352",
        "price": 479.99,
        "name": "Україна - VWX234",
        "rate": 4.7,
        "wheelRadius": 26,
        "weight": 14.9
    },
    {
        "_id": "9",
        "id": "9",
        "stockNumber": "ST12353",
        "count": 6,
        "description": "Bike description",
        "manufacturer": "Manufacturer I",
        "partNumber": "PN12353",
        "price": 499.99,
        "name": "Україна - YZA567",
        "rate": 4.5,
        "wheelRadius": 29,
        "weight": 16.3
    },
    {
        "_id": "10",
        "id": "10",
        "stockNumber": "ST12354",
        "count": 9,
        "description": "Bike description",
        "manufacturer": "Manufacturer J",
        "partNumber": "PN12354",
        "price": 529.99,
        "name": "Україна - BCD890",
        "rate": 4.4,
        "wheelRadius": 27.5,
        "weight": 15.7
    },
    {
        "_id": "11",
        "id": "11",
        "stockNumber": "ST12355",
        "count": 14,
        "description": "Bike description",
        "manufacturer": "Manufacturer K",
        "partNumber": "PN12355",
        "price": 559.99,
        "name": "Україна - EFG123",
        "rate": 4.6,
        "wheelRadius": 26,
        "weight": 15.0
    },
    {
        "_id": "12",
        "id": "12",
        "stockNumber": "ST12356",
        "count": 3,
        "description": "Bike description",
        "manufacturer": "Manufacturer L",
        "partNumber": "PN12356",
        "price": 579.99,
        "name": "Україна - HIJ456",
        "rate": 4.9,
        "wheelRadius": 29,
        "weight": 16.2
    },
    {
        "_id": "13",
        "id": "13",
        "stockNumber": "ST12357",
        "count": 4,
        "description": "Bike description",
        "manufacturer": "Manufacturer M",
        "partNumber": "PN12357",
        "price": 599.99,
        "name": "Україна - KLM789",
        "rate": 4.3,
        "wheelRadius": 27.5,
        "weight": 15.6
    },
    {
        "_id": "14",
        "id": "14",
        "stockNumber": "ST12358",
        "count": 2,
        "description": "Bike description",
        "manufacturer": "Manufacturer N",
        "partNumber": "PN12358",
        "price": 629.99,
        "name": "Україна - NOP012",
        "rate": 4.7,
        "wheelRadius": 26,
        "weight": 14.6
    },
    {
        "_id": "15",
        "id": "15",
        "stockNumber": "ST12359",
        "count": 18,
        "description": "Bike description",
        "manufacturer": "Manufacturer O",
        "partNumber": "PN12359",
        "price": 649.99,
        "name": "Україна - QRS345",
        "rate": 4.8,
        "wheelRadius": 29,
        "weight": 16.1
    },
    {
        "_id": "16",
        "id": "16",
        "stockNumber": "ST12360",
        "count": 17,
        "description": "Bike description",
        "manufacturer": "Manufacturer P",
        "partNumber": "PN12360",
        "price": 679.99,
        "name": "Україна - TUV678",
        "rate": 4.9,
        "wheelRadius": 27.5,
        "weight": 15.8
    },
    {
        "_id": "17",
        "id": "17",
        "stockNumber": "ST12361",
        "count": 13,
        "description": "Bike description",
        "manufacturer": "Manufacturer Q",
        "partNumber": "PN12361",
        "price": 699.99,
        "name": "Україна - WXY901",
        "rate": 4.6,
        "wheelRadius": 26,
        "weight": 15.2
    },
    {
        "_id": "18",
        "id": "18",
        "stockNumber": "ST12362",
        "count": 16,
        "description": "Bike description",
        "manufacturer": "Manufacturer R",
        "partNumber": "PN12362",
        "price": 729.99,
        "name": "Україна - ZAB234",
        "rate": 4.5,
        "wheelRadius": 29,
        "weight": 16.0
    },
    {
        "_id": "19",
        "id": "19",
        "stockNumber": "ST12363",
        "count": 19,
        "description": "Bike description",
        "manufacturer": "Manufacturer S",
        "partNumber": "PN12363",
        "price": 749.99,
        "name": "Україна - CDE567",
        "rate": 4.4,
        "wheelRadius": 27.5,
        "weight": 15.9
    },
    {
        "_id": "20",
        "id": "20",
        "stockNumber": "ST12364",
        "count": 22,
        "description": "Bike description",
        "manufacturer": "Manufacturer T",
        "partNumber": "PN12364",
        "price": 779.99,
        "name": "Україна - FGH890",
        "rate": 4.7,
        "wheelRadius": 26,
        "weight": 15.3
    },
    {
        "_id": "21",
        "id": "21",
        "stockNumber": "ST12365",
        "count": 25,
        "description": "Bike description",
        "manufacturer": "Manufacturer U",
        "partNumber": "PN12365",
        "price": 799.99,
        "name": "Україна - IJK123",
        "rate": 4.8,
        "wheelRadius": 29,
        "weight": 16.4
    },
    {
        "_id": "22",
        "id": "22",
        "stockNumber": "ST12366",
        "count": 23,
        "description": "Bike description",
        "manufacturer": "Manufacturer V",
        "partNumber": "PN12366",
        "price": 829.99,
        "name": "Україна - LMN456",
        "rate": 4.9,
        "wheelRadius": 27.5,
        "weight": 16.2
    },
    {
        "_id": "23",
        "id": "23",
        "stockNumber": "ST12367",
        "count": 24,
        "description": "Bike description",
        "manufacturer": "Manufacturer W",
        "partNumber": "PN12367",
        "price": 849.99,
        "name": "Україна - OPQ789",
        "rate": 4.5,
        "wheelRadius": 26,
        "weight": 15.7
    },
    {
        "_id": "24",
        "id": "24",
        "stockNumber": "ST12368",
        "count": 21,
        "description": "Bike description",
        "manufacturer": "Manufacturer X",
        "partNumber": "PN12368",
        "price": 879.99,
        "name": "Україна - RST012",
        "rate": 4.6,
        "wheelRadius": 29,
        "weight": 16.3
    }
];

export default products;